HugoGresse/open-feedback

- .eslintrc.example
- README.md
- config/firestore.rules
- package.json
- src/admin/AdminApp.js
- src/admin/ProjectAdd.js
- src/admin/ProjectAddEditContent.js
- src/admin/ProjectDashboard.js
- src/admin/ProjectEdit.js
- src/admin/SideBar.js
- src/admin/auth/Login.js
- src/admin/notification/Notifications.js
- src/admin/notification/notifcationActions.js
- src/admin/notification/notificationActionTypes.js
- src/admin/notification/notificationReducer.js
- src/admin/notification/notificationSelectors.js
- src/admin/projectCore/projectActionTypes.js
- src/admin/projectCore/projectActions.js
- src/admin/projectCore/projectReducer.js
- src/rootReducer.js
Project can now be edited or created.
Only Hoverboard-v2 can be configured, nex PR is to add custom hand-made project
> Project edit add

- package-lock.json
- package.json
- src/App.js
- src/admin/notification/Notifications.js
- src/admin/project/dashboard/ProjectDashboard.js
- src/baseComponents/customComponent/Snackbar.js
- src/baseComponents/design/PaperButton.js
- src/constants/constants.js
- src/feedback/AppLayout.js
- src/feedback/session/SessionVoteBoolean.js
- src/feedback/session/SessionVoteText.js
- src/feedback/sessions/SessionsItem.js
- src/feedback/sessions/SessionsList.js
Migrate to MUI v4. 
I'm not changing the import, having trouble finding what's the best way to go along with CRA. 
Close #68
> Update MUI to v4

- src/admin/AdminApp.js
- src/core/sessions/sessionsActionTypes.js
- src/feedback/AppLayout.js
- src/feedback/session/Session.js
- src/feedback/session/SessionVoteBackground.js
- src/feedback/session/SessionVoteText.js
- src/feedback/sessions/SessionsListWrapper.js
- src/root/Root.js
Fix Most deprecation warning related to componentWillMount & componentWillReceiveProps
See #90
> #90 component will deprecated methods

- src/App.js
- src/admin/project/talks/TalkList.js
- src/admin/project/talks/TalkListItem.js
- src/admin/project/talks/Talks.js
- src/core/sessions/sessionsSelectors.js
- src/core/setupType/hoverboardv2/Hoverboardv2Api.js
- src/firebase.js
On the admin, the Talks page now display the talk in a read only mode
> Admin: list talks

- package.json
- scripts/.gitignore
- scripts/helpers/initFirestore.ts
- scripts/helpers/updates.ts
- scripts/package-lock.json
- scripts/package.json
- scripts/serviceAccountKey.json.example
- scripts/tsconfig.json
- scripts/update-voteItems-out-of-collections.2019.ts
- src/admin/project/Project.js
- src/admin/project/core/projectActions.js
- src/admin/project/settings/votingForm/votingFormActionTypes.js
- src/admin/project/settings/votingForm/votingFormActions.js
- src/admin/project/settings/votingForm/votingFormReducer.js
- src/feedback/project/projectActionTypes.js
- src/feedback/project/projectActions.js
- src/feedback/project/projectReducer.js
- src/feedback/session/Session.js
- src/utils/stringUtils.js
> Tech: change voteItems from subCollection to an array in project

- src/admin/project/Project.js
- src/admin/project/core/projectActions.js
- src/admin/project/settings/event/ChipColorsEditor.js
- src/admin/project/settings/event/ProjectSettingsForm.js
- src/utils/colorsUtils.js
When a new event was created, no ChipColors was added causing an error when voting. 
This fix this + add the createdAt time for new project
Fix #192
> Default chip color for newproject

- src/admin/baseComponents/FormikObserver.js
- src/admin/notification/Notifications.js
- src/admin/project/core/projectActions.js
- src/admin/project/core/projectSelectors.js
- src/admin/project/new/Step3.js
- src/admin/project/new/Step3Hoverboardv2.js
- src/admin/project/new/Step3JSON.js
- src/admin/project/settings/setup/Setup.js
- src/admin/project/settings/setup/SetupForm.js
- src/admin/project/settings/setup/SetupTypeBox.js
- src/admin/project/setupTypeForms/SetupHoverboardv2.js
- src/admin/project/setupTypeForms/SetupHoverboardv2Form.js
- src/admin/project/setupTypeForms/SetupJSON.js
- src/admin/project/setupTypeForms/SetupJSONForm.js
- src/admin/project/setupTypeForms/validation/SetupValidation.js
- src/admin/project/setupTypeForms/validation/SetupValidationContainer.js
- src/admin/project/setupTypeForms/validation/validationString.js
- src/core/setupType/hoverboardv2/Hoverboardv2Api.js
- src/core/setupType/jsonurl/JsonUrlApi.js
- src/core/setupType/projectApi.js
- src/core/setupType/validation.js
- src/utils/stringUtils.js
> Admin: add setup page + validation on project creation and setup

- functions/package-lock.json
- package-lock.json
- package.json
- src/admin/project/setupTypeForms/SetupJSONForm.js
- src/admin/project/setupTypeForms/jsonmodel.json
> Admin: Add copy button to json model

- src/admin/project/settings/votingForm/VoteItem.js
- src/admin/project/settings/votingForm/VoteItemList.js
Close #206 
It's pretty handy and was not so hard todo.
> Admin: add a new input when pressing enter in current input in the Voting Form

- package-lock.json
- package.json
- src/admin/baseComponents/OFDateTimePickerFormiked.js
- src/admin/baseComponents/OFFormControlFormiked.js
- src/admin/baseComponents/OFFormControlInputFormiked.js
- src/admin/baseComponents/OFInput.js
- src/admin/baseComponents/OFInputForDateTimePicker.js
- src/admin/baseComponents/RadioButtonGroup.js
- src/admin/project/new/Step1.js
- src/admin/project/new/Step2.js
- src/admin/project/settings/event/ProjectSettingsForm.js
- src/admin/project/settings/setup/SetupForm.js
- src/admin/project/setupTypeForms/SetupHoverboardv2Form.js
- src/admin/project/setupTypeForms/SetupJSONForm.js
Fix #208 
isSubmitting was not working after migration to formik v2
Error message is now in red + additional error message on the event & theme screen
Date range picker is now disabled when form is submitting
Formik from 2.0.3 to 2.0.4
> #208 Admin form improvement + fix

- .github/workflows/build.yml
- .gitignore
- lighthouse/budget.json
- lighthouse/lighthouserc.json
- lighthouserc.json
Close #210 
it miss the diff with master :/
> Add lighthouseci config + github action config

- config/firestore.rules
- package-lock.json
- src/admin/auth/authActions.js
- src/feedback/layout/Footer.js
This prepare the user administration. 
The user is now saved in db in order to get his information (real name, photo) when listing all members of a project.
> Admin: Save admin user in db

- src/admin/project/dashboard/DashboardCard.js
- src/admin/project/dashboard/Highlights.js
- src/admin/project/dashboard/MostVotedSessions.js
- src/admin/project/dashboard/ProjectDashboard.js
- src/admin/project/dashboard/VoteTimeline.js
- src/admin/project/dashboard/dashboardSelectors.js
- src/utils/numberUtils.js
> Add hightlights to dashboard

- .github/workflows/test-e2e.yml
- config/firestore.rules
- cypress/support/commands.js
- lighthouse/budget.json
- package-lock.json
- package.json
- src/admin/adminReducer.js
- src/admin/auth/authActions.js
- src/admin/baseComponents/layouts/OFListHeader.js
- src/admin/baseComponents/layouts/OFListItem.js
- src/admin/project/core/projectActions.js
- src/admin/project/core/projectSelectors.js
- src/admin/project/settings/users/UserItem.js
- src/admin/project/settings/users/UserList.js
- src/admin/project/settings/users/UserListHeader.js
- src/admin/project/settings/users/Users.js
- src/admin/project/settings/users/usersActionTypes.js
- src/admin/project/settings/users/usersActions.js
- src/admin/project/settings/users/usersReducer.js
- src/admin/project/settings/users/usersSelectors.js
- src/admin/project/talks/TalkList.js
- src/admin/project/talks/TalkListItem.js
- src/admin/project/talks/Talks.js
- src/feedback/session/SessionVoteTextResult.js
This PR display the current users/members of an event. 
User can now be removed from a project but not currently added (this will come by EOM)
Also fix the word being cut in feedback comment
> Admin: list users + remove button + feedback word cut fix

- .prettierrc
- config/firestore.rules
- functions/package-lock.json
- functions/package.json
- src/admin/project/layout/SideBar.js
- src/admin/project/settings/users/UserInviteItem.js
- src/admin/project/settings/users/UserInviteList.js
- src/admin/project/settings/users/Users.js
- src/admin/project/settings/users/usersActionTypes.js
- src/admin/project/settings/users/usersActions.js
- src/admin/project/settings/users/usersReducer.js
- src/admin/project/settings/users/usersSelectors.js
- src/admin/root/ProjectInviteDialog.js
> Admin:  user invite list

- src/admin/auth/authActions.js
- src/admin/project/layout/SideBar.js
- src/admin/root/RootHeader.js
This prevent having to check inside providerData in the rest of the base code
> Fill user.displayName & photoURL from user or provider data upon admin login

- src/App.js
- src/admin/AdminApp.js
- src/admin/AdminLayout.js
- src/admin/SuspendedAdminApp.js
- src/admin/project/layout/SideBar.js
- src/baseComponents/customComponent/ErrorBoundaryWithGame.js
- src/baseComponents/customComponent/LoaderMatchParent.js
Fix #168 
This reduce the feedback JS from 2mB to 1.4mB which is good
It also fix the loading component that should be delayed by 500ms before showing up.
> Add suspens on admin + catch react error component

- src/App.test.js
- src/admin/baseComponents/layouts/OFListHeader.js
- src/admin/baseComponents/layouts/OFListItem.js
- src/admin/project/settings/votingForm/VoteItem.js
- src/admin/project/settings/votingForm/VoteItemList.js
- src/admin/project/speakers/SpeakerList.js
- src/admin/project/speakers/SpeakerListItem.js
- src/baseComponents/customComponent/ErrorBoundary.js
> Admin list refacto to use OFListHeader and OFListItem

- src/App.js
- src/admin/AdminApp.js
- src/admin/project/Project.js
- src/admin/project/ProjectApp.js
- src/admin/project/layout/Layout404.js
- src/admin/project/layout/ProjectLayout.js
- src/admin/root/AdminRoot.js
- src/admin/root/RootContent.js
> Fix #234 Admin routing 404 + remove useless theme

- src/admin/auth/EmailNotVerified.js
- src/admin/auth/Login.js
- src/admin/auth/authActions.js
- src/admin/auth/authSelectors.js
- src/admin/root/AdminRoot.js
- src/admin/root/ProjectList.js
- src/admin/root/RootContentLayout.js
Fix #240 & #278 
- User was not able to get projects because their token was not refreshed
- User email verification page was ugly
- Login component was not using hook
- 🛑login now use redirect to reduce friction on browser
> Admin: Proper user email verification page + refresh token when user come back + tech refacto + auth redirect

- src/admin/project/new/NewProject.js
- src/admin/project/talks/TalkList.js
- src/admin/project/talks/TalkListItem.js
- src/admin/project/talks/TalkListItemSpeakerList.js
> Admin fix (404, speaker filter click & chip color)

- src/admin/project/settings/users/UserInvitePanel.js
SidePanel to add admin to a project where not displaying anything...
> Admin: fix user sidepanel not showing anything

- functions/package-lock.json
- src/admin/baseComponents/DinoBackground.js
- src/admin/project/ProjectApp.js
- src/admin/project/core/projectActionTypes.js
- src/admin/project/core/projectActions.js
- src/admin/project/core/projectReducer.js
- src/admin/project/dashboard/Dashboard.js
- src/admin/project/dashboard/Highlights.js
- src/admin/project/dashboard/MostVotedTalks.js
- src/admin/project/dashboard/VoteTimeline.js
- src/admin/project/dashboard/dashboardSelectors.js
- src/admin/project/dashboard/utils/DashboardCard.js
- src/admin/project/dashboard/utils/DinoBackground.js
- src/admin/project/dashboard/utils/NoData.js
- src/admin/project/new/NewProject.js
- src/admin/project/settings/event/ProjectSettingsForm.js
- src/admin/project/settings/votingForm/votingFormActions.js
- src/feedback/layout/Header.js
> Fill voting form with example when creating a new project + remove required scheduleLink + add Dino

- config/firestore.rules
- src/admin/baseComponents/OFButton.js
- src/admin/project/core/projectActions.js
- src/admin/project/settings/setup/DeleteProject.js
- src/admin/project/settings/setup/Setup.js
- src/admin/translations/languages/en/en.json
- src/admin/translations/languages/fr/fr.json
> Add delete functionnality & button

- cypress/integration/admin/newproject.spec.js
- src/admin/baseComponents/form/OFFormControlFormiked.js
- src/admin/baseComponents/form/OFFormControlInputFormiked.js
- src/admin/project/core/projectActions.js
- src/admin/project/new/NewProject.js
- src/admin/project/new/Step1.js
- src/admin/project/new/Step1.projectIdChange.js
- src/admin/translations/languages/en/en.json
- src/admin/translations/languages/fr/fr.json
Fix #381 
New event can now picked a custom id (a-z-0-9-) if available. It will always be lower case when custom id is generated.
> #381 Custom event id 

- cypress/integration/feedback/talk.spec.js
- src/admin/baseComponents/layouts/OFListHeader.js
- src/admin/translations/languages/fr/fr.json
- src/feedback/FeedbackApp.js
- src/feedback/layout/Footer.js
- src/feedback/layout/SearchBar.js
- src/feedback/talk/TalkVoteText.js
- src/feedback/translations/i18n.js
- src/feedback/translations/languages/en/en.json
- src/feedback/translations/languages/fr/fr.json
Input search in speakers/talks/user now have a "close" button to remove input value
> [Admin] Add remove input search in admin

- src/root/FAQ.js
- src/root/translations/fr/fr.json
> Marketing Website: small redesign of the FAQ

- src/admin/project/settings/event/ColorBlockDialog.js
> Admin: Remove color picker box shadow and improve color drag perf

- src/admin/project/settings/setup/DeleteProject.js
previously: it was kind of random and we needed to wait for a long time without any info.
> [Admin] Add loader on event delete

- functions/package-lock.json
- src/admin/project/settings/votingForm/votingFormReducer.js
Fix a bug that will take last selected project voting form and add them to a new created project
> [Admin] Clear votingForm on project unselect

- firebase.json
- public/404.html
- public/index.html
- public/robots.txt
- src/App.js
- src/baseComponents/HardRedirect.js
- src/feedback/AppLayout.js
- src/feedback/project/projectActionTypes.js
- src/feedback/project/projectReducer.js
- src/feedback/project/projectSelectors.js
- src/root/Header.js
> [Landing] Add SEO tags

- functions/package-lock.json
- package-lock.json
- package.json
- src/admin/AdminApp.js
- src/admin/notification/Notifications.js
- src/admin/project/dashboard/Dashboard.js
- src/admin/project/dashboard/dashboardSelectors.js
- src/admin/project/dashboard/utils/TalkVotesList.js
- src/admin/project/layout/ProjectLayout.js
- src/admin/project/settings/votingForm/votingFormSelectors.js
- src/feedback/project/projectReducer.js
- [Admin] Change page title based on selected project
- [Admin] Fix: number of pages not rounded on dashboard tiles
- [Admin] Fix: Dashboard comment count not correct (due to not only one Text vote since last PR) #490 
- [Admin] Dashboard: move graph/timeline on the first line on large screen.
> Admin minor fixes/improvement

- src/admin/project/speakers/SpeakerAddEditPanel.js
- src/admin/project/speakers/SpeakerList.js
- src/admin/translations/languages/en/en.json
- src/admin/translations/languages/fr/fr.json
- src/core/talks/talksActions.js
- src/utils/mapUtils.js
- notify the user if the speaker to remove is linked to any talk, close #266 
- remove mandatory photo url
> [Admin] Check linked talk when removing speaker && remove mandatory photo url

- public/index.html
fonts, firestore, login/auth
Close #506
> [Tech] Add preconnect to index.html for Google domains

- cypress/integration/feedback/talks.spec.js
- functions/package-lock.json
- src/core/talks/talksSelectors.js
- src/feedback/talks/SearchExtendedMatch.js
- src/feedback/talks/SearchNoMatch.js
- src/feedback/talks/TalksList.js
- src/feedback/talks/TalksListWrapper.js
- src/feedback/translations/languages/en/en.json
- src/feedback/translations/languages/fr/fr.json
Prior to this PR, the search only searched within the selected day, this fix this and check all day and list relatd talk at the end of the list. 
Close #511
> [Feedback] Add extended results for a given search (check the other day)

- src/admin/SuspendedAdminApp.js
- src/baseComponents/customComponent/ErrorBoundary.js
- src/feedback/FeedbackApp.js
- src/root/SuspendedRootApp.js
- src/utils/alerting/alerts.js
Alert is sent to OpsGenie which trigger an email to Hugo.
> [Tech] Catch react error on feedback app + send alert

- functions/package-lock.json
- package-lock.json
fixed 3 of 24 vulnerabilities in 965103 scanned packages
> Update dependences to fix some vulnerabilities

- src/admin/notification/Notifications.js
- src/admin/notification/notifcationActions.js
- src/admin/notification/notificationActionTypes.js
- src/admin/notification/notificationReducer.js
- src/admin/notification/notificationSelectors.js
- src/admin/project/core/projectActions.js
- src/admin/project/moderation/moderationActions.js
- src/admin/project/settings/users/usersActions.js
- src/admin/project/settings/votingForm/votingFormActions.js
- src/core/speakers/speakerActions.js
- src/core/talks/talksActions.js
fix
- click on the page no longer close the notification
- exit animation
- reduce code by using addNotification always
- better handle multiple notification stack
> [Admin] Refactor notification

- src/admin/auth/authActions.js
- src/admin/notification/Notifications.js
- src/admin/project/core/projectActions.js
- src/admin/project/moderation/moderationActions.js
- src/admin/project/new/NewProject.js
- src/admin/project/settings/users/usersActions.js
- src/admin/project/settings/votingForm/votingFormActions.js
- src/admin/translations/languages/en/en.json
- src/admin/translations/languages/fr/fr.json
- src/feedback/AppLayout.js
this also include support for translation in Notification & translation support through this.
> [Admin] Translate most of admin errors in French

- src/admin/project/settings/event/ProjectSettingsForm.js
- src/admin/project/talks/TalkAddEditPanel.js
- src/admin/translations/languages/en/en.json
- src/admin/translations/languages/fr/fr.json
- Wording fix on missing translation
- fix trackTitle "null" value reporting an error on form submit
> [Admin] Wording fix + talk trackTitle fix

- src/feedback/talk/Talk.js
- src/feedback/translations/languages/en/en.json
- src/feedback/translations/languages/fr/fr.json
- src/feedback/vote/checkDataBeforeVote.js
- src/feedback/vote/voteActions.js
- vote error and not translate enable
- fix vote period check timezone
> [Feedback] Translate vote error + fix vote range check timezone issue

- public/index.html
- src/admin/project/new/NewProject.js
- src/admin/translations/languages/en/en.json
- src/admin/translations/languages/fr/fr.json
wording change on landing title, admin project type
OpenFeedback project type is selected by default now
> Wording + Admin default event type set to OpenFeedback

- src/feedback/speaker/SpeakerItem.js
- src/feedback/speaker/SpeakerList.js
- src/feedback/talk/Talk.js
When clicking on a speaker from a single talk, it open it's social profil, if any
> [Feedback] Add link to socialProfil on speaker

- src/admin/baseComponents/form/dateTimePicker/OFDateTimePicker.js
- src/admin/baseComponents/form/dateTimePicker/OFInputForDateTimePicker.js
- src/admin/project/core/actions/editProject.js
- src/admin/project/core/projectSelectors.js
- src/admin/project/settings/event/ProjectSettingsForm.js
- src/admin/project/settings/event/RestrictVoteRangeFields.js
- src/admin/project/talks/TalkAddEditPanel.js
- src/admin/project/talks/TalkList.js
- src/admin/project/talks/TalkStartEndTimeFields.js
Fix #608
- Vote range end time now change to the start time on start time change
- Talk start time is project start time if filled
- Talk end time default to start time on start time change
> [Admin] Improve date management on event vote range & talk dates

- .github/workflows/build.yml
this should improve install perf
> [Tech] Replace npm install by npm ci on github actions

- src/admin/translations/languages/en.admin.json
- src/admin/translations/languages/fr.admin.json
> Admin: Change "add & continue" wording

- public/index.html
- src/admin/project/new/Step2.js
- src/admin/translations/languages/en.admin.json
- src/admin/translations/languages/fr.admin.json
Full screen dialog title "Create a new event (step 2/2)" change based on selected project.
> Meta change + fix new project step count

- src/admin/baseComponents/layouts/sidepanel/upload/SidePanelUploadLayout.js
- src/admin/translations/languages/en.admin.json
- src/admin/translations/languages/fr.admin.json
Uplaod error was not catch and nothing happened upon error. This PR solve this by catching the issue and adding a user notification upon error which should hopefully help him.
> [Admin] Catch upload error and add notification upon error

- public/index.html
This should slithy improve page load speed
> Use font swap & remove Material Icon font

- src/root/FAQ.js
- src/root/translations/languages/en.root.json
- src/root/translations/languages/fr.root.json
> [Landing] Add custom SDK to FAQ

- .github/workflows/build.yml
- package-lock.json
- package.json
- src/admin/project/setupTypeForms/SetupJSONForm.js
- src/admin/project/setupTypeForms/jsonmodel.json
- src/admin/project/setupTypeForms/validation/SetupValidationContainer.js
- src/admin/project/setupTypeForms/validation/validationString.js
- src/core/setupType/validation.js
- src/core/setupType/validation.test.js
Fix #660
This is the first PR that add unit test /o/
> [Admin] Fix optionals data keys for json/hoverboard validation & add test on it

- src/admin/project/core/projectUtils.js
- src/admin/project/new/Step1.js
- src/admin/translations/languages/en.admin.json
- src/admin/translations/languages/fr.admin.json
Fix #632 
[Admin] Custom event id must no be more than 3 char & not a reserved keyword
> [Admin] Add reserved projects ids and restrict minimum char count for project ids

- cypress.json
- cypress/integration/admin/newproject.spec.js
- cypress/integration/admin/votingForm.spec.js
- cypress/support/AdminApp.Settings.js
- cypress/support/AdminApp.VotingForm.js
- cypress/support/AdminApp.js
- cypress/support/FeedbackApp.js
- cypress/support/commands.js
- cypress/utils/generateString.js
- src/admin/auth/EmulatorLogin.js
- src/admin/auth/Login.js
- src/admin/baseComponents/layouts/OFListItem.js
- src/admin/project/layout/ProjectLayout.js
- src/admin/project/settings/votingForm/VoteItem.js
- src/feedback/talk/TalkVoteBoolean.js
- src/feedback/talk/TalkVoteText.js
- new classes for cypress test
- more test on voting form in it's own spec file
- ignore firebase ui error
> Add test on VotingForm + some new test classes

- cypress/support/AdminApp.EventTheme.js
- package-lock.json
- package.json
- cypress 6.3.0 
- - fix event-theme calendar day pick/click
> Update cypress  + fix event teme calendar picker

- src/admin/project/dashboard/LeastVotedTalks.js
- src/admin/project/dashboard/MostCommentedTalks.js
- src/core/speakers/speakerSelectors.js
- src/core/talks/talksSelectors.js
> Fix undefined talks or speakers from json

- cypress/integration/admin/event-theme.spec.js
- cypress/integration/admin/votingForm.spec.js
- cypress/support/AdminApp.EventTheme.js
- cypress/support/AdminApp.Settings.js
- cypress/support/AdminApp.VotingForm.js
- cypress/support/commands.js
- cypress/utils/triggerSaveKeyPress.js
- package-lock.json
- package.json
- src/admin/baseComponents/form/saveShortcut/SaveShortcut.js
- src/admin/project/settings/event/ProjectSettingsForm.js
- src/admin/project/settings/votingForm/VoteItemList.js
- src/admin/project/settings/votingForm/VotingForm.js
- src/admin/project/settings/votingForm/VotingFormTranslationTip.js
- src/admin/project/settings/votingForm/votingFormActions.js
- src/admin/project/settings/votingForm/votingFormSelectors.js
- src/admin/project/utils/rURLWithLocalhostSupported.js
- src/admin/translations/languages/en.admin.json
- src/admin/translations/languages/fr.admin.json
- Add a tip on top on the voting form to inform that translation lang can be added in the settings. Close #929 
- Add cmd+s / ctrl+s shortcut on voting form. Closing #928
-  Add cmd+s / ctrl+s shortcut on settings. Closing #928
Discard  #927 (will not do yet)
> Admin: voting form langs tips + save shortcut + save button in header

- src/admin/baseComponents/form/autoComplete/OFAutoComplete.js
- src/admin/baseComponents/layouts/sidepanel/SidePanelLayout.js
- src/admin/organization/core/actions/newOrganization.js
- src/admin/organization/core/organizationReducer.js
- src/admin/organization/core/organizationSelectors.js
- src/admin/organization/theme/OrganizationTheme.js
- src/admin/organization/users/OrganizationUsers.js
- src/admin/project/core/actions/getProject.js
- src/admin/project/core/actions/getProjectOrganizationIfPossible.js
- src/admin/project/core/actions/newProject.js
- src/admin/project/core/actions/selectUnselectProject.js
- src/admin/project/layout/Header.js
- src/admin/project/settings/users/ProjectUsers.js
- src/admin/project/talks/TalkAddEditPanel.js
- src/admin/users/UserInvitePanel.js
- src/admin/users/UserListHeader.js
- src/admin/users/components/UserAutocompleteOption.js
- src/admin/users/core/usersSelectors.js
- fix new event error within an org
- display organization name in event header
- autocomplete event users for invites, see video below
https://user-images.githubusercontent.com/662377/110216639-752a9180-7eb0-11eb-9bea-c3e75972f1f8.mov
> [Admin] Autocomplete user in organizations event user screen + fix event creation in org

- src/admin/project/speakers/SpeakerAddEditPanel.js
- src/admin/project/talks/TalkAddEditPanel.js
> [Admin] Add autofocus on speaker & talk first input

- src/feedback/AppLayout.js
- src/feedback/FeedbackApp.js
- src/feedback/talk/TalkVoteText.js
Loading screen on feedback app had a white background color, this is now fixed. 
Close #1119
> [Feedback] Fix dark mode on feedback loader

- src/admin/translations/i18n.js
- src/feedback/translations/i18n.js
- src/root/Header.js
- src/root/translations/i18n.js
- src/utils/newI18nInstance.js
(also change the demo project link for the root app if using the emulators)
Close #1114
> [Tech] Use the same i18n config for the three apps

- src/admin/project/dashboard/utils/TalkVotesList.js
- src/admin/project/moderation/TalkListItem.js
- src/admin/project/talks/TalkListItem.js
- src/feedback/speaker/SpeakerItem.js
- src/feedback/speaker/SpeakerList.js
- src/feedback/talk/Talk.js
- src/feedback/talk/TalkHeader.js
- src/feedback/talks/TalksItem.js
- src/feedback/translations/languages/en.feedback.json
- src/feedback/translations/languages/fr.feedback.json
> [Feedback & Admin] Fix overflow for long talk name or too much speakers

- src/feedback/layout/Header.js
- src/feedback/utils/isInIFrame.js
Close #181 
Improve iframe support, which is already possible, jsut improve the UI
> [Feedback] Improve iframe support

- src/admin/project/core/actions/newProject.js
- src/admin/utils/track.js
- src/root/Menu.js
> [Landing] Github link in menu

- src/admin/root/ProjectList.js
> [Admin] Fix new event buttons colors

- src/admin/translations/languages/en.admin.json
- src/admin/translations/languages/fr.admin.json
- src/feedback/AppLayout.js
- src/feedback/layout/Footer.js
- src/feedback/project/projectReducer.js
- src/feedback/talk/text/VoteTextResultItem.js
- src/feedback/translations/languages/en.feedback.json
- src/feedback/translations/languages/fr.feedback.json
- fix #1409 : old project/event does not have a "plus" field in the aggregated vote, thus clicking on it produced undesired values. 
- add "Donate" link on feedback footer:
> Fix NaN on comment upvote for existing project + add donate link on feedback footer

- config/firestore.rules
- config/firestore.rules.spec.js
- src/admin/project/core/actions/resetProjectVotes.js
- src/admin/project/settings/setup/ResetVotes.js
- src/admin/project/settings/setup/Setup.js
- src/admin/translations/languages/en.admin.json
- src/admin/translations/languages/fr.admin.json
Closes #1473 
Done:
- new firestore rules for sessionVotes and userVotes for delete operation
> [Admin] Reset votes

- src/core/setupType/jsonurl/JsonUrlApi.js
- src/feedback/talk/TalkHeader.js
- src/utils/stringUtils.js
#1492  fix "null" in Json speakers array in sessions crashing both backend and frontend 
#1152 fix invalidDateTime if startTime supplied without endTime
> 1492 1152 invalid date time json url keep string only

- src/feedback/talk/text/VoteTextResultItem.js
> feat(#1528): reflect the vote count on VoteText

- README.md
@gerardpaligot is doing all the heavylifting these days ❤️ . Also switch from "Android" to "Kotlin" as KMM is coming 👀
> Update README.md for Android/Kotlin SDK

- src/admin/project/dashboard/dashboardSelectors.js
only in the admin app dashboard.
> Fix createdAt on aggregated user vote being null in some case crashing the UI

- package-lock.json
- package.json
- src/core/talks/talksSelectors.js
- src/feedback/talks/TalksList.jsx
- src/feedback/talks/TalksListWrapper.jsx
- sort talk by start minutes in talk list (within tracks and dates)
> feature: Sort talk by start minutes in talk list (within tracks and dates)

- .env
- src/admin/project/layout/SideBar.jsx
- src/admin/root/RootHeader.jsx
- src/admin/translations/languages/en.admin.json
- src/admin/translations/languages/fr.admin.json
- src/baseComponents/useOSSSponsors.ts
- src/env.ts
- src/feedback/layout/Footer.jsx
- src/feedback/translations/languages/en.feedback.json
- src/feedback/translations/languages/fr.feedback.json
- src/root/HowItWorks.jsx
- src/root/Root.jsx
- src/root/Sponsor.jsx
- src/root/translations/languages/en.root.json
- src/root/translations/languages/fr.root.json
- display open source sponsor on OpenFeedback
> Display OSS sponsors

- src/admin/project/layout/SideBar.jsx
- src/baseComponents/useOSSSponsors.ts
- src/feedback/layout/Footer.jsx
- src/root/Sponsor.jsx
- add click tracking to project sponsors
> Add tracking to sponsors
